/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Volcano(props) {
  const { nodes, materials } = useGLTF('/models/Volcano.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.volcano.geometry} material={materials.None} />
    </group>
  )
}

useGLTF.preload('/Volcano.glb')
