/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Boat(props) {
  const { nodes, materials } = useGLTF('/models/Boat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Boat.geometry} material={materials.lambert3SG} />
    </group>
  )
}

useGLTF.preload('/models/Boat.glb')
