/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Boombox = forwardRef(({ onClick, ...props }, ref) => {
  const { nodes, materials } = useGLTF('/models/Boombox.glb')
  return (
    <group {...props} ref={ref} dispose={null} onClick={onClick}>
      <mesh castShadow receiveShadow geometry={nodes.Boombox_mesh.geometry} material={materials.Boombox_mat} />
    </group>
  )
})
Boombox.displayName = 'Boombox'
useGLTF.preload('/models/Boombox.glb')
