/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
export function Boombox({ ...props }) {
  const { nodes, materials } = useGLTF('/models/Boombox.glb')
  // eslint-disable-next-line no-console
  console.log('materials: ', materials)

  const [introAudio, setIntroAudio] = useState(null)
  const boomRef = useRef()
  const outlineRef = useRef()
  const [isPlaying, setIsPlaying] = useState(false)
  const [isHovering, setIsHovering] = useState(false)

  useFrame(() => {
    if (outlineRef.current) {
      outlineRef.current.material.opacity = THREE.MathUtils.lerp(
        outlineRef.current.material.opacity,
        isHovering || isPlaying ? 0.75 : 0.15,
        0.1,
      )
    }
  })

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const audio = new Audio('/voiceover.wav')
      audio.preload = 'auto'
      setIntroAudio(audio)
      const handleEnded = () => setIsPlaying(false)
      audio.addEventListener('ended', handleEnded)

      return () => {
        audio.pause()
        audio.removeEventListener('ended', handleEnded)
      }
    }
  }, [])

  const handleBoomboxClick = (event) => {
    event.stopPropagation()
    if (!introAudio) {
      return
    }
    if (isPlaying) {
      introAudio.pause()

      setIsPlaying(false)
    } else {
      introAudio.play().catch((error) => {
        setIsPlaying(false)
      })
      setIsPlaying(true)
    }
  }

  return (
    <group
      {...props}
      dispose={null}
      onClick={handleBoomboxClick}
      onPointerOver={() => setIsHovering(true)}
      onPointerOut={() => setIsHovering(false)}
      ref={boomRef}
    >
      <mesh castShadow receiveShadow geometry={nodes.Boombox_mesh.geometry} material={materials.Boombox_mat} />
      <mesh ref={outlineRef} geometry={nodes.Boombox_mesh.geometry} scale={1.04}>
        <meshBasicMaterial color='#fefef1' transparent opacity={0.2} side={THREE.BackSide} toneMapped={false} />
      </mesh>
      {/* <mesh
        ref={outlineRef}
        geometry={nodes.Boombox_mesh.geometry}
        scale={1.05} // Slightly larger
      >
        <meshBasicMaterial color='#4040ff' transparent opacity={0.2} side={THREE.BackSide} toneMapped={false} />
      </mesh> */}
    </group>
  )
}
Boombox.displayName = 'Boombox'
useGLTF.preload('/models/Boombox.glb')
