/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

const ACTION_MAP = {
  yes: 'CharacterArmature|CharacterArmature|CharacterArmature|Yes',
  wave: 'CharacterArmature|CharacterArmature|CharacterArmature|Wave',
  walkHolding: 'CharacterArmature|CharacterArmature|CharacterArmature|Walk_Holding',
  walk: 'CharacterArmature|CharacterArmature|CharacterArmature|Walk',
  sword: 'CharacterArmature|CharacterArmature|CharacterArmature|Sword',
  sittingStart: 'CharacterArmature|CharacterArmature|CharacterArmature|Sitting_Start',
  sittingIdle: 'CharacterArmature|CharacterArmature|CharacterArmature|Sitting_Idle',
  assemblyEnd: 'CharacterArmature|CharacterArmature|CharacterArmature|Assembly_End',
  assemblyLoop: 'CharacterArmature|CharacterArmature|CharacterArmature|Assembly_Loop',
  assemblyStart: 'CharacterArmature|CharacterArmature|CharacterArmature|Assembly_Start',
  chopEnd: 'CharacterArmature|CharacterArmature|CharacterArmature|Chop_End',
  chopLoop: 'CharacterArmature|CharacterArmature|CharacterArmature|Chop_Loop',
  chopStart: 'CharacterArmature|CharacterArmature|CharacterArmature|Chop_Start',
  death: 'CharacterArmature|CharacterArmature|CharacterArmature|Death',
  duck: 'CharacterArmature|CharacterArmature|CharacterArmature|Duck',
  hitReact: 'CharacterArmature|CharacterArmature|CharacterArmature|HitReact',
  idle: 'CharacterArmature|CharacterArmature|CharacterArmature|Idle',
  idleHolding: 'CharacterArmature|CharacterArmature|CharacterArmature|Idle_Holding',
  jump: 'CharacterArmature|CharacterArmature|CharacterArmature|Jump',
  jumpIdle: 'CharacterArmature|CharacterArmature|CharacterArmature|Jump_Idle',
  jumpLand: 'CharacterArmature|CharacterArmature|CharacterArmature|Jump_Land',
  no: 'CharacterArmature|CharacterArmature|CharacterArmature|No',
  panEnd: 'CharacterArmature|CharacterArmature|CharacterArmature|Pan_End',
  panLoop: 'CharacterArmature|CharacterArmature|CharacterArmature|Pan_Loop',
  panStart: 'CharacterArmature|CharacterArmature|CharacterArmature|Pan_Start',
  punch: 'CharacterArmature|CharacterArmature|CharacterArmature|Punch',
  run: 'CharacterArmature|CharacterArmature|CharacterArmature|Run',
  runHolding: 'CharacterArmature|CharacterArmature|CharacterArmature|Run_Holding',
  sittingEating: 'CharacterArmature|CharacterArmature|CharacterArmature|Sitting_Eating',
  sittingEnd: 'CharacterArmature|CharacterArmature|CharacterArmature|Sitting_End',
}

export function Bunny(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Bunny.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const waveAction = actions[ACTION_MAP['wave']]
    const idleAction = actions[ACTION_MAP['idle']]
    if (waveAction && idleAction) {
      idleAction.play()
      waveAction.reset().setLoop(THREE.LoopOnce, 1).play()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Root_Scene'>
        <group name='RootNode'>
          <group name='CharacterArmature' rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <skinnedMesh
            name='Rabbit'
            geometry={nodes.Rabbit.geometry}
            material={materials.AtlasMaterial}
            skeleton={nodes.Rabbit.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <skinnedMesh
            name='Eyes'
            geometry={nodes.Eyes.geometry}
            // material={materials.AtlasMaterial}
            material={new THREE.MeshBasicMaterial({ map: materials.AtlasMaterial.map })}
            skeleton={nodes.Eyes.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <skinnedMesh
            name='Hair'
            geometry={nodes.Hair.geometry}
            // material={materials.AtlasMaterial}
            // material={new THREE.MeshStandardMaterial({ color: 'blue' })}
            material={new THREE.MeshBasicMaterial({ map: materials.AtlasMaterial.map })}
            skeleton={nodes.Hair.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

Bunny.displayName = 'Bunny'
useGLTF.preload('/models/Bunny.glb')
