/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Dolphin(props) {
  const { nodes, materials } = useGLTF('/models/Dolphin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Geo_Dolphin.geometry} material={materials.lambert2SG} />
    </group>
  )
}

useGLTF.preload('/models/Dolphin.glb')
