/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

const ACTIONS = [
  'DragonArmature|Dragon_Attack',
  'DragonArmature|Dragon_Attack2',
  'DragonArmature|Dragon_Flying',
  'DragonArmature|Dragon_Death',
  'DragonArmature|Dragon_Hit',
]

export function Dragon(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Dragon.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {}, [actions])

  const handleClick = (event) => {
    event.stopPropagation()
    const randomNumber = Math.floor(Math.random() * 5)

    const actionName = ACTIONS[randomNumber]
    const action = actions[actionName]
    if (action) {
      action.reset().setLoop(THREE.LoopOnce, 1).play()
    }
  }
  return (
    <group ref={group} {...props} dispose={null} onClick={handleClick}>
      <group name='Root_Scene'>
        <group name='RootNode'>
          <group name='DragonArmature' rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <group name='Dragon' position={[0, 1.584, -0.219]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name='Dragon_1'
              geometry={nodes.Dragon_1.geometry}
              material={materials.Main}
              skeleton={nodes.Dragon_1.skeleton}
            />
            <skinnedMesh
              name='Dragon_2'
              geometry={nodes.Dragon_2.geometry}
              material={materials.Belly}
              skeleton={nodes.Dragon_2.skeleton}
            />
            <skinnedMesh
              name='Dragon_3'
              geometry={nodes.Dragon_3.geometry}
              material={materials.Claws}
              skeleton={nodes.Dragon_3.skeleton}
            />
            <skinnedMesh
              name='Dragon_4'
              geometry={nodes.Dragon_4.geometry}
              material={materials.Wings}
              skeleton={nodes.Dragon_4.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

Dragon.displayName = 'Dragon'
useGLTF.preload('/models/Dragon.glb')
