/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: denys4624 (https://sketchfab.com/denys4624)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/komodo-a3bb3a390dd1466e9bbab4a994329d45
Title: Komodo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/komodo.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-2.969, -621.232, 461.78]} scale={2.6}>
          <group position={[1.142, 238.935, -177.608]} scale={0.385}>
            <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.Material_2044} />
            <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.Material_2049} />
            <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.Material_2050} />
            <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.KOMOLEFT} />
            <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.KOMOTOP} />
            <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.KOMOBOTT} />
            <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.KOMOLEG} />
            <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.Material_2043} />
            <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.Material_2045} />
            <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.Material_2046} />
            <mesh castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials.Material_2047} />
            <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials.KOMOARM} />
            <mesh castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials.Material_2048} />
            <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials.Material_2051} />
            <mesh castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials.Material_2052} />
          </group>
          <group position={[85.707, 1734.157, 460.065]}>
            <group position={[-15.838, 0, 0]}>
              <group position={[1.141, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.KOMOGLS}
                  position={[-69.868, -1495.222, -637.673]}
                  scale={0.385}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_24.geometry}
                material={materials.KOMOEYE}
                position={[-68.728, -1495.222, -637.673]}
                scale={0.385}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_26.geometry}
              material={materials.KOMOPUPL}
              position={[-84.565, -1495.222, -637.673]}
              scale={0.385}
            />
          </group>
          <group position={[-81.113, 1734.157, 460.065]}>
            <group position={[15.838, 0, 0]}>
              <group position={[-1.141, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_31.geometry}
                  material={materials.KOMOGLS}
                  position={[67.558, -1495.222, -637.673]}
                  scale={0.385}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_33.geometry}
                material={materials.KOMOEYE}
                position={[66.417, -1495.222, -637.673]}
                scale={0.385}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_35.geometry}
              material={materials.KOMOPUPL}
              position={[82.255, -1495.222, -637.673]}
              scale={0.385}
            />
          </group>
          <group position={[373.485, 1264.527, -485.129]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_38.geometry}
              material={materials.KOMOCLAW}
              position={[-372.343, -1025.591, 307.521]}
              scale={0.385}
            />
          </group>
          <group position={[346.589, 1310.769, -485.11]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_41.geometry}
              material={materials.KOMOCLAW}
              position={[-345.447, -1071.834, 307.502]}
              scale={0.385}
            />
          </group>
          <group position={[286.718, 1341.037, -485.469]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_44.geometry}
              material={materials.KOMOCLAW}
              position={[-285.576, -1102.101, 307.861]}
              scale={0.385}
            />
          </group>
          <group position={[225.507, 1340.372, -485.039]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_47.geometry}
              material={materials.KOMOCLAW}
              position={[-224.365, -1101.436, 307.431]}
              scale={0.385}
            />
          </group>
          <group position={[170.024, 1222.147, -482.407]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_50.geometry}
              material={materials.KOMOCLAW}
              position={[-168.882, -983.212, 304.799]}
              scale={0.385}
            />
          </group>
          <group position={[-169.775, 1222.147, -482.407]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_53.geometry}
              material={materials.KOMOCLAW}
              position={[170.917, -983.212, 304.799]}
              scale={0.385}
            />
          </group>
          <group position={[-225.258, 1340.372, -485.039]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_56.geometry}
              material={materials.KOMOCLAW}
              position={[226.4, -1101.436, 307.431]}
              scale={0.385}
            />
          </group>
          <group position={[-286.469, 1341.037, -485.469]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_59.geometry}
              material={materials.KOMOCLAW}
              position={[287.611, -1102.101, 307.861]}
              scale={0.385}
            />
          </group>
          <group position={[-346.341, 1310.769, -485.11]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_62.geometry}
              material={materials.KOMOCLAW}
              position={[347.483, -1071.834, 307.502]}
              scale={0.385}
            />
          </group>
          <group position={[542.778, 504.684, -476.496]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_65.geometry}
              material={materials.KOMOCLAW}
              position={[-541.636, -265.749, 298.888]}
              scale={0.385}
            />
          </group>
          <group position={[354.382, 664.597, -482.941]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_68.geometry}
              material={materials.KOMOCLAW}
              position={[-353.24, -425.662, 305.333]}
              scale={0.385}
            />
          </group>
          <group position={[420.667, 713.837, -485.084]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_71.geometry}
              material={materials.KOMOCLAW}
              position={[-419.525, -474.901, 307.476]}
              scale={0.385}
            />
          </group>
          <group position={[492.245, 727.091, -485.084]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_74.geometry}
              material={materials.KOMOCLAW}
              position={[-491.103, -488.156, 307.476]}
              scale={0.385}
            />
          </group>
          <group position={[560.998, 705.65, -485.084]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_77.geometry}
              material={materials.KOMOCLAW}
              position={[-559.856, -466.714, 307.476]}
              scale={0.385}
            />
          </group>
          <group position={[-541.643, 504.684, -476.496]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_80.geometry}
              material={materials.KOMOCLAW}
              position={[542.785, -265.749, 298.888]}
              scale={0.385}
            />
          </group>
          <group position={[-373.236, 1264.527, -485.129]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_83.geometry}
              material={materials.KOMOCLAW}
              position={[374.378, -1025.591, 307.521]}
              scale={0.385}
            />
          </group>
          <group position={[-353.247, 664.597, -482.941]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_86.geometry}
              material={materials.KOMOCLAW}
              position={[354.389, -425.662, 305.333]}
              scale={0.385}
            />
          </group>
          <group position={[-419.531, 713.837, -485.084]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_89.geometry}
              material={materials.KOMOCLAW}
              position={[420.673, -474.901, 307.476]}
              scale={0.385}
            />
          </group>
          <group position={[-491.11, 727.091, -485.084]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_92.geometry}
              material={materials.KOMOCLAW}
              position={[492.252, -488.156, 307.476]}
              scale={0.385}
            />
          </group>
          <group position={[-559.863, 705.65, -485.084]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_95.geometry}
              material={materials.KOMOCLAW}
              position={[561.005, -466.714, 307.476]}
              scale={0.385}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/komodo.glb')
