/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/Sign.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={100}>
        <mesh castShadow receiveShadow geometry={nodes.Sign12_1.geometry} material={materials['Light Wood']} />
        <mesh castShadow receiveShadow geometry={nodes.Sign12_2.geometry} material={materials['Dark Wood']} />
        <mesh castShadow receiveShadow geometry={nodes.Sign12_3.geometry} material={materials.Herbs} />
        <mesh castShadow receiveShadow geometry={nodes.Sign12_4.geometry} material={materials.Rocks} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Sign.glb')
