/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/Turtle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['Node-Mesh'].geometry} material={materials.lambert5SG} />
      <mesh castShadow receiveShadow geometry={nodes['Node-Mesh_1'].geometry} material={materials.lambert3SG} />
      <mesh castShadow receiveShadow geometry={nodes['Node-Mesh_2'].geometry} material={materials.lambert4SG} />
      <mesh castShadow receiveShadow geometry={nodes['Node-Mesh_3'].geometry} material={materials.lambert6SG} />
      <mesh castShadow receiveShadow geometry={nodes['Node-Mesh_4'].geometry} material={materials.lambert2SG} />
      <mesh castShadow receiveShadow geometry={nodes['Node-Mesh_5'].geometry} material={materials.lambert7SG} />
    </group>
  )
}

useGLTF.preload('/models/Turtle.glb')
